/**:
  ros__parameters:
    camera_name: "camera_front_left"
    frame_id: "camera/camera_link"
    pixel_format: bgr8
    serial_no: 221400788
    camera_info_url: "file:///home/robotaxi/robotaxi/src/lucid_vision_driver/config/camera_fl.yaml"
    fps: 10
    horizontal_binning: 4 # resize horizontal resolution/horizontal_binning
    vertical_binning: 4 # resize horizontal resolution/vertical_binning
    enable_rectifying: true
    enable_compressing: true
    use_default_device_settings: true
    # if you use_default_device_settings: true, the following settings are ignored.
    # ROS driver will use the default device settings of the camera.
    exposure_auto: true
    exposure_target: 187
    gain_auto: true
    gain_target: 1
    gamma_target: 1.0
    image_horizontal_flip: false
    image_vertical_flip: false
